Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "name"
          "AttributeType": "S",
                             - "AttributeName": "password"
                               "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "userName"
          "KeyType": "S"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "ToolDatabase"

