Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "toolId"
          "AttributeType": "N"
        - "AttributeName": "owner"
          "AttributeType": "S"
        - "AttributeName": "toolName"
          "AttributeType": "S"
        - "AttributeName": "isAvailable"
          "AttributeType": "BOOL"
        - "AttributeName": "description"
          "AttributeType": "S"
        - "AttributeName": "comments"
          "AttributeType": "L"
        - "AttributeName": "borrower"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "toolId"
          "KeyType": "N"
      GlobalSecondaryIndexes:
        - IndexName: Owner
          KeySchema:
            - AttributeName: owner
              KeyType: S
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "ToolDatabase"

